'use client';

import React from 'react';
import { FileText, Download } from 'lucide-react';

export default function ExportedReportsPage() {
  const exportsList = [
    { id: 'EXP-1042', name: 'Special_Audit_Dossier_C1042_ABC_Supplies.pdf', date: '2026-02-18 11:45 AM', size: '3.4 MB', author: 'Dr. Sunita Deshmukh' },
    { id: 'EXP-1041', name: 'Triage_Queue_Critical_Summary_FY26.csv', date: '2026-02-17 05:20 PM', size: '1.2 MB', author: 'Rajesh Sharma' },
    { id: 'EXP-1040', name: 'Vendor_Cartel_Graph_Export_V001.pdf', date: '2026-02-16 02:10 PM', size: '5.1 MB', author: 'Rajesh Sharma' }
  ];

  return (
    <div className="space-y-5">
      <div className="bg-white p-5 rounded-lg border border-slate-200 shadow-2xs">
        <div className="flex items-center gap-2 mb-1">
          <span className="text-2xs font-bold uppercase tracking-wider text-slate-500 bg-slate-100 px-2 py-0.5 rounded">
            ARCHIVE
          </span>
        </div>
        <h2 className="text-lg font-bold text-slate-900">Exported Investigation Dossiers</h2>
        <p className="text-xs text-slate-600 mt-0.5">
          Archived audit memos, CSV exports, and evidence dossiers.
        </p>
      </div>

      <div className="bg-white border border-slate-200 rounded-lg shadow-2xs overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left gov-table">
            <thead>
              <tr>
                <th>Dossier File Name</th>
                <th>Export Date</th>
                <th>File Size</th>
                <th>Generated By</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {exportsList.map(item => (
                <tr key={item.id} className="hover:bg-slate-50/80">
                  <td className="font-semibold text-xs text-slate-900">{item.name}</td>
                  <td className="font-mono text-2xs text-slate-500">{item.date}</td>
                  <td className="font-mono text-2xs text-slate-600">{item.size}</td>
                  <td className="text-xs text-slate-700">{item.author}</td>
                  <td>
                    <button
                      onClick={() => alert(`Downloading ${item.name}...`)}
                      className="inline-flex items-center gap-1 text-2xs font-bold text-navy-900 hover:underline"
                    >
                      <Download className="w-3 h-3" />
                      <span>Download File</span>
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
